jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 5000
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysqldbgestcomp}:${MYSQL_PORT:3306}/${DB_NAME:pfeDataBase}?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:root} #change this to your database password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    
    
   
